// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD88TbfPttxtZO2Qpme0a17dbG_ABkjSY',
    appId: '1:761587132325:web:d17133d1fa22fe0611ea4c',
    messagingSenderId: '761587132325',
    projectId: 'maptestge',
    authDomain: 'maptestge.firebaseapp.com',
    storageBucket: 'maptestge.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbmKJz1RVg_qXyl2yAk3_V6UiZctL15V8',
    appId: '1:761587132325:android:e28d46083ff37ed111ea4c',
    messagingSenderId: '761587132325',
    projectId: 'maptestge',
    storageBucket: 'maptestge.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD5PD5KRLQXyAIMTzQqO6sW6j5Pxl1Ge8',
    appId: '1:761587132325:ios:c4de89552a39e17911ea4c',
    messagingSenderId: '761587132325',
    projectId: 'maptestge',
    storageBucket: 'maptestge.appspot.com',
    iosBundleId: 'com.example.rideShare',
  );
}
